PRAGMA user_version = 2;

CREATE TABLE roles (
	id INTEGER PRIMARY KEY,
	slug TEXT NOT NULL,
	name TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)

INSERT INTO roles (slug, name)
VALUES ('SUPERADMIN', 'Superadmin')('ADMIN', 'Admin'),('PAIDUSER', 'Paid user'),('FREEUSER', 'Fre user');

CREATE TABLE users (
	id INTEGER PRIMARY KEY,
	uid, TEXT NOT NULL,
	username TEXT UNIQUE NOT NULL,
	passwordHash TEXT NOT NULL,
	email, TEXT,
	role
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
