PRAGMA foreign_keys = ON;

CREATE TABLE highscores (
	id INTEGER PRIMARY KEY,
	socket_id TEXT NOT NULL,
	username TEXT NOT NULL,
	score INTEGER DEFAULT 0 NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

