apiVersion: apps/v1
kind: Deployment
metadata:
  name: joukko-deployment
  labels:
    app: joukko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joukko
  template:
    metadata:
      labels:
        app: joukko
    spec:
      containers:
      - name: joukko
        image: leoalho/joukkoio:joukko
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: USER_NAME
          value: root
        - name: USER_PWD
          value: example

---
apiVersion: v1
kind: Service
metadata:
  name: joukko-service
spec:
  type: NodePort
  selector:
    app: joukko
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100